@startuml 类图
title 异常继承图


class Object
{
    ' +void operation1();
    ' +int operation2(int i);

    ' -int attribute1;
    ' -char attribute2;
}
class Error 
{

}

class Exception
{

}

' 虚拟机错误
class VirtualMachinError
{

}

' note "测试效果222" as N1
Object <|-- Throwable
note right: 不管是错误还是异常都是可抛出的。
' Throwable .. N1
' N1 .. Object

Throwable <|-- Error
note left
    所有错误只要发生，java程序只有一个结果，那
    就是终止程序的运行，退出JVM，错误是不能处理的。
end note
Error<|-- VirtualMachinError
VirtualMachinError<|-- StcakOverflowError
Error<|-- IOError
Throwable <|-- Exception
Exception <|-- RuntimeException
note top:所有RuntimeException及子类都属于运行时异常
RuntimeException <|-- NullPointerException
RuntimeException <|-- ClassCastException
RuntimeException <|-- IllegalArgumentException
IllegalArgumentException <|-- NumberFormatException

' ExceptionSubClass不是某一个类，泛指很多类
Exception <|-- ExceptionSubClass
note right
    note 1 ExceptionSubClass不是某一个类，泛指Exception的直接子类
    note 2 所有ExceptionSubClass的直接子类，都叫做编译异常
end note

@enduml

